services:
  - type: web
    name: freaky-furniture-projekt
    runtime: docker
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS  
        value: http://0.0.0.0:$PORT

  - type: web
    name: freaky-furniture-projekt-1
    runtime: static
    plan: free
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: ./client/dist/client/browser
    envVars:
      - key: NODE_VERSION
        value: "18"