// <auto-generated />
using System;
using FreakyFurnitureAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreakyFurnitureAPI.Migrations
{
    [DbContext(typeof(FurnitureDbContext))]
    [Migration("20250927163759_AddProductsAndCategories")]
    partial class AddProductsAndCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreakyFurnitureAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlSlug")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UrlSlug")
                        .IsUnique()
                        .HasFilter("[UrlSlug] IS NOT NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 526, DateTimeKind.Utc).AddTicks(3457),
                            Name = "Sofas",
                            UpdatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 526, DateTimeKind.Utc).AddTicks(3715),
                            UrlSlug = "sofas"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 526, DateTimeKind.Utc).AddTicks(3953),
                            Name = "Chairs",
                            UpdatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 526, DateTimeKind.Utc).AddTicks(3953),
                            UrlSlug = "chairs"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 526, DateTimeKind.Utc).AddTicks(3955),
                            Name = "Tables",
                            UpdatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 526, DateTimeKind.Utc).AddTicks(3955),
                            UrlSlug = "tables"
                        });
                });

            modelBuilder.Entity("FreakyFurnitureAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PublishingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlSlug")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasFilter("[Sku] IS NOT NULL");

                    b.HasIndex("UrlSlug")
                        .IsUnique()
                        .HasFilter("[UrlSlug] IS NOT NULL");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "FreakyFurniture",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 902, DateTimeKind.Utc).AddTicks(7020),
                            Description = "A comfortable modern sofa perfect for any living room.",
                            Image = "/images/modern-sofa.jpg",
                            Name = "Modern Sofa",
                            Price = 899.99m,
                            UpdatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 902, DateTimeKind.Utc).AddTicks(7365),
                            UrlSlug = "modern-sofa"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "FreakyFurniture",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 902, DateTimeKind.Utc).AddTicks(7696),
                            Description = "Ergonomic office chair with lumbar support.",
                            Image = "/images/office-chair.jpg",
                            Name = "Office Chair",
                            Price = 299.99m,
                            UpdatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 902, DateTimeKind.Utc).AddTicks(7698),
                            UrlSlug = "office-chair"
                        });
                });

            modelBuilder.Entity("FreakyFurnitureAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 755, DateTimeKind.Utc).AddTicks(9245),
                            Password = "$2a$11$xqjaOVVDwIb2SsvJiF9W6uTOwDStGVvfoKo1UewvDB3C4QkxvwQt.",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 27, 16, 37, 58, 902, DateTimeKind.Utc).AddTicks(363),
                            Password = "$2a$11$v7Fb6/GbfJWgW7BAKIxDYeI4fPR6O1C1jhaYZNUTy4g4Ly61I3N9O",
                            Role = "user",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("FreakyFurnitureAPI.Models.Product", b =>
                {
                    b.HasOne("FreakyFurnitureAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FreakyFurnitureAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
